website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from .models import User
from .forms import LoginForm, RegisterForm, CreateEventForm
from . import db

# Create a blueprint - make sure all BPs have unique names
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        uname = register_form.username.data
        email = register_form.email.data
        pwd = register_form.password.data
        # utype = register_form.usertype.data
        # Check if username or email already exists
        existing_user = User.query.filter_by(name=uname).first()
        if existing_user:
            flash("Username already taken", "error")
            return render_template('register.html', form=register_form, heading='Register')

        # Hash the password for security
        pwd_hash = generate_password_hash(pwd)
        
        # Create a new User object and add it to the session
        new_user = User(name=uname, emailid=email, password_hash=pwd_hash)
        db.session.add(new_user)
        db.session.commit()
        print("added data to database") 
        flash("Registered user successfully", "success")
        
        login_user(new_user )
        return redirect(url_for('main.index'))
    else:
        print(register_form.errors)  # Display any validation errors

    # Flash validation errors, if any
    for field, errors in register_form.errors.items():
        for error in errors:
            flash(f"{field}: {error}", "error")
    
    return render_template('register.html', form=register_form, heading='Register', user=None)



@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    error=None
    if(form.validate_on_submit()):
        user_name = form.user_name.data
        password = form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        
        #if there is no user with that name
        if u1 is None:
            error='Incorrect user name'
        #check the password - notice password hash function
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
        #all good, set the login_user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            print(error)
            flash(error)
        #it comes here when it is a get method
    return render_template('user.html', form=form, heading='Login', user=None)


@auth_bp.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from .forms import CreateComment, LoginForm, CreateOrder, CreateEventForm
from .models import Event, Comment, User, Order
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from datetime import datetime
from . import db, CATEGORIES
import os


main_bp = Blueprint('main', __name__)

# Helper function to check if user is authenticated
def check_login(current_user):
    return current_user if current_user.is_authenticated else None

# Index route, displays all events
@main_bp.route('/')
def index():
    category = request.args.get("category")
    search_keywords = request.args.get("search_keywords")
    if category or search_keywords:
        if category != "None" and search_keywords != "None":
            events = Event.query.filter(Event.Title.contains(search_keywords)).filter_by(Category=category).order_by(Event.id).all()
        elif category != "None":
            events = Event.query.filter_by(Category=category).order_by(Event.id).all()
        elif search_keywords != "None":
            events = Event.query.filter(Event.Title.contains(search_keywords)).order_by(Event.id).all()
        else:
            events = Event.query.order_by(Event.id).all()
    else:
            events = Event.query.order_by(Event.id).all()
    
    user = check_login(current_user)
    
    for event in events:
        if event.Start_date.strftime('%Y-%m-%d') < datetime.today().strftime('%Y-%m-%d') and event.Status != "Inactive":
            new_event = Event.query.filter_by(id=event.id).first()
            new_event.Status = "Inactive"
            db.session.add(new_event)
            
    db.session.commit()
    
    out_events = [{"event": event, "img_location": "/".join(event.Image.split("\\")[2:4])} for event in events]
    
    
    return render_template('index.html', events=out_events, user=user, categories=CATEGORIES, category=category, search_keywords=search_keywords)


@main_bp.route('/create-event', methods=['GET', 'POST'])
def CreateEvent():
    form = CreateEventForm()
    if form.validate_on_submit():
        # Process form data
        title = form.event_title.data
        description = form.event_description.data
        start_date = form.event_date.data
        start_time = form.event_time.data
        venue = form.event_venue.data
        category = form.event_genre.data
        tickets_available = form.tickets_available.data

        # Handle image upload
        image_file = form.event_image.data
        if image_file:
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image_file.save(image_path)
        else:
            image_path = 'default.jpg'  # Path to a default image if needed

        # Create an Event object
        new_event = Event(
            Title=title,
            Description=description,
            Image=image_path,
            Start_date=start_date,
            Start_time=start_time,
            Venue=venue,
            Category=category,
            Tickets_available=tickets_available,
            Status="Open",
            user_id=current_user.id  # assuming logged-in user
        )

        # Add and commit the new event to the database
        db.session.add(new_event)
        db.session.commit()
        
        flash("Event created successfully!", "success")
        return redirect(url_for('main.index'))

    # If validation fails, flash errors
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{field}: {error}", "error")

    return render_template('create.html', form=form)


@main_bp.route('/create-user')
def createUser():
    return render_template('register.html', form=CreateUser)


# Event details page, shows event information and allows order and comment submission
@main_bp.route('/details', methods=['GET', 'POST'])
def eventDetails():
    event_id = request.args.get('id')
    event = Event.query.filter_by(id=event_id).first()
    order_form = CreateOrder()
    comment_form = CreateComment()
    user = check_login(current_user)
    event_creator = User.query.filter_by(id=event.user_id).first()
    
    img_location = "/".join(event.Image.split("\\")[2:4])

    if event == None:
        return redirect(url_for('main.notFound'))
        
        
    error = ""
    # Handling ticket orders
    if order_form.validate_on_submit() and 'tickets' in request.form:
        tickets = order_form.tickets.data
        event_id = request.args.get('id')
        event = Event.query.filter_by(id=event_id).first()

        if event.Status == "Inactive":
            error = "This event is inactive"
        elif event.Status == "Cancelled":
            error = "This event has expired"
        elif tickets is None:
            error = "No tickets selected"
        elif not user:
            error = "You must login to purchase tickets"
        elif event.Tickets_available <= 0:
            error = "This event is sold out"
        elif tickets > event.Tickets_available:
            error = "Not enough tickets available to fulfill your request"

        if error == "":
            order = Order(
                tickets=tickets,
                user_id=user.id,
                event_id=event_id
            )
            event.Tickets_available -= tickets
            if event.Tickets_available <= 0:
                event.Status = "Sold Out"
            db.session.add(order)
            db.session.commit()
            return redirect(url_for('main.orderDetails') + '?id=' + str(order.id))
        else:
            flash(error)

    # Get comments and poster details
    comments = Comment.query.filter_by(event_id=event_id).all()
    comment_dicts = [
        {
            "poster": User.query.filter_by(id=comment.user_id).first().name,
            "comment": comment.comment,
            "date_posted": comment.date_posted,
        }
        for comment in comments
    ]
    return render_template('details.html', event=event, user=user, order_form=order_form, comment_form=comment_form, comments=comment_dicts, event_creator=event_creator, status=event.Status, img_location=img_location)

# Profile page, accessible only when logged in, and passes user data to the template
@main_bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user)

# History page - shows the user's past orders
@main_bp.route('/history')
@login_required
def history():
    user_orders = Order.query.filter_by(user_id=current_user.id).all()
    orders = []
    for order in user_orders:
        orders.append({
            "order": order,
            "event": Event.query.filter_by(id=order.event_id).first()
            })
    return render_template('history.html', orders=orders)

@main_bp.route('/eventcr-history')
@login_required
def history2():
    # Query all events created by the current user
    user_events = Event.query.filter_by(user_id=current_user.id).all()
    return render_template('eventcr_history.html', events=user_events)



# Comment partial view route
@main_bp.route('/comments', methods=['GET', 'POST'])
def Comments():
    comment_form = CreateComment()
    user = check_login(current_user)
    event_id = request.args.get('id')
    
    error = ""
    if comment_form.validate_on_submit():
        comment_text = comment_form.comment.data
        if comment_text is None:
            error = "Please enter a comment"
        elif not user:
            error = "You must login to post comments"

        if error == "":
            new_comment = Comment(
                comment=comment_text,
                date_posted=datetime.now(),
                event_id=event_id,
                user_id=user.id
            )
            db.session.add(new_comment)
            db.session.commit()
        else:
            flash(error)
            
    comments = Comment.query.filter_by(event_id=event_id).all()
    comment_dicts = [
        {
            "poster": User.query.filter_by(id=comment.user_id).first().name,
            "comment": comment.comment,
            "date_posted": comment.date_posted
        }
        for comment in comments
    ]
    
    return render_template('partials/comments.html', comment_form=comment_form, comments=comment_dicts, user=user)

# Order details route
@main_bp.route('/order', methods=['GET'])
def orderDetails():
    order_id = request.args.get('id')
    order = Order.query.filter_by(id=order_id).first()
    event = Event.query.filter_by(id=order.event_id).first()
    user = check_login(current_user)
    
    return render_template('order.html', order=order, event=event, user=user)


@main_bp.route('/404')
def notFound():
    return render_template("404.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IAB207 Assignment 3</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
</head>

<body>
    <!-- Header -->
    <header>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Cook and Connect Events</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.CreateEvent') }}">Create an Event</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.history') }}">Event History</a>
                        </li>
                    </ul>
                    <div class="d-flex gap-2">
                        {% if user != None %}
                            <a href="{{ url_for('main.profile') }}" class="btn btn-outline-light">Profile</a>
                            <a href="{{ url_for('auth.logout') }}" class="btn btn-outline-light">Logout</a>
                        {% else %}
                            <a href="{{ url_for('auth.login') }}" class="btn btn-outline-light">Login</a>
                            <a href="{{ url_for('auth.register') }}" class="btn btn-outline-light">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <!-- Code for using Flask flash -->
        <!-- <div class="container-fluid">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div> -->
        {% block header %}
        {% endblock %}

    </header>
    <!-- padding added to bottom of content to stop footer displaying over content -->
    <div class="pb-5"> 
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-dark text-white text-center py-3">
        © 2024
    </footer>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>

website/templates/create.html
{% extends "base.html" %}

{% block content %}

    <!-- Event Creation -->
    <div class="form-container">
        <h2 class="text-center mb-4">Create Event</h2>
        <form method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
            
            <div class="form-group mb-3">
                {{ form.event_image.label(class="form-label") }}
                {{ form.event_image(class="form-control") }}
                {% for error in form.event_image.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        
            <div class="form-group mb-3">
                {{ form.event_title.label(class="form-label") }}
                {{ form.event_title(class="form-control", placeholder="Enter event title") }}
                {% for error in form.event_title.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        
            <div class="form-group mb-3">
                {{ form.event_description.label(class="form-label") }}
                {{ form.event_description(class="form-control", rows="4", placeholder="Enter event description") }}
                {% for error in form.event_description.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        
            <div class="row mb-3">
                <div class="col-md-6">
                    {{ form.event_date.label(class="form-label") }}
                    {{ form.event_date(class="form-control") }}
                    {% for error in form.event_date.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
        
                <div class="col-md-6">
                    {{ form.event_time.label(class="form-label") }}
                    {{ form.event_time(class="form-control") }}
                    {% for error in form.event_time.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
        
            <div class="form-group mb-3">
                {{ form.event_venue.label(class="form-label") }}
                {{ form.event_venue(class="form-control", placeholder="Enter event venue") }}
                {% for error in form.event_venue.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        
            <div class="form-group mb-3">
                {{ form.event_genre.label(class="form-label") }}
                {{ form.event_genre(class="form-select") }}
                {% for error in form.event_genre.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        
            <div class="form-group mb-3">
                {{ form.tickets_available.label(class="form-label") }}
                {{ form.tickets_available(class="form-control", placeholder="Enter number of tickets available") }}
                {% for error in form.tickets_available.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>        
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Create Event</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/details.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row g-4">
            <!-- Event Details Card -->
            <div class="col-md-8">
                <div class="card p-4">
                    <h1 class="event-header">{{ event.Title }}</h1>
                    <img src="{{ url_for('static', filename=img_location) }}" class="img-fluid rounded mb-3" alt="Event Image" style="max-width: 300px; max-height: 300px;">
                    <p class="mb-3">{{ event.Description }}</p>
                    <p><strong>Artist: </strong>{{ event_creator.name }}</p>
                    <p><strong>Date & Time: </strong>{{ event.Start_date }}: {{ event.Start_time }}</p>
                    <p><strong>Location: </strong>{{ event.Venue }}</p>
                    <p><strong>Tickets Available: </strong>{{ event.Tickets_available }}</p>
                </div>
            </div>  
            <!-- Booking Section -->
            {% if status == "Open" %}
            <div class="col-md-4">
                <div class="card p-4">
                    <h1 class="event-header">Book Your Tickets</h1>
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                          {% for message in messages %}
                              <div class="alert alert-danger">
                              {{ message }}
                            </div>
                          {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {{wtf.quick_form(order_form)}}
                </div>
            </div>
            {% else %}
            <div class="col-md-4" style="opacity: 0.3;">
                <div class="card p-4">
                    <h1 class="event-header">Book Your Tickets</h1>
                
                    <div class="alert alert-danger">
                        <p>This event is {{ status }}</p>
                    </div>

                    <label class="control-label" for="tickets">Ticket Quantity</label>
                    <input class="form-control" id="tickets" name="tickets" required="" type="number" value="" disabled>
                    <input class="btn btn-default" id="submit" name="submit" type="submit" value="Post" disabled>
                </div>
            </div>

            {% endif %}
            <!-- Comments Section -->
            <div class="col-12 pb-5">
                <div class="card p-4">
                    <h1 class="event-header">Comments</h1>
                    <iframe src="{{ url_for( 'main.Comments') }}?id={{ event.id }}" width="100%" height="500"></iframe>
                </div>
            </div>
        </div>
        <script>
            function clearTickets() {
                document.getElementById("tickets").value = null
            }
            window.onload = clearTickets;
        </script>
    </div>

{% endblock %}

website/templates/eventcr_history.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">
    <!-- Page Header -->
    <div class="bg-light-header text-center">
        <h1>Your Created Events</h1>
        <p class="lead">View all of the events you have created.</p>
        <a href="{{ url_for('main.index') }}" class="btn-find-more">Find More</a>
    </div>

    <!-- Event History Section -->
    {% if events %}
        <div class="row g-4">
            {% for event in events %}
                <div class="col-md-6 col-lg-4">
                    <div class="card p-3">
                        <h3 class="card-title"><strong>Title:</strong> {{ event.Title }}</h3>
                        <p><strong>Date:</strong> {{ event.Start_date }}</p>
                        <p><strong>Time:</strong> {{ event.Start_time }}</p>
                        <p><strong>Location:</strong> {{ event.Venue }}</p>
                        <p><strong>Status:</strong> {{ event.Status }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="no-events-message">
            No Created Events
        </div>
    {% endif %}
</div>
{% endblock %}

website/templates/history.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">
    <!-- Page Header -->
    <div class="bg-light-header text-center">
        <h1>Your booking History</h1>
        <p class="lead">View all the bookings yiou have made in the past.</p>
        <a href="{{ url_for('main.index') }}" class="btn-find-more">Find More</a>
    </div>

    <!-- Event History Section -->
    {% if orders %}
        <div class="row g-4">
            {% for user_order in orders %}
                <div class="col-md-6 col-lg-4">
                    <div class="card p-3">
                        <h3 class="card-title"><strong>order number: </strong>{{ user_order.order.id }}</h3>
                        <p><strong>Date:</strong> {{ user_order.event.date }}</p>
                        <p><strong>Location:</strong> {{ user_order.event.Venue }}</p>
                        <p><strong>Status:</strong> {{ user_order.event.Status }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="no-events-message">
            No Past Events
        </div>
    {% endif %}
</div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block header %}
<div class="top-section">
    <div class="py-2">
        <!-- Search Bar -->
        <div class="search-bar">
            <input type="text" id="searchInput" placeholder="Search events">
            <button id="searchButton" onclick="search()">Search</button>
        </div>

        <!-- Banner  -->
        <div class="banner-content">
            <h1>Find the Best Culinary Events</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <!-- Actions -->
    <h3 class="category-title">Categories</h3>
    <div class="categories">
        
        {% for category in categories %}
            <div class="category-item">
            <a class="btn-default" href="{{ url_for('main.index') }}?category={{ category.0 }}&search_keywords={{ search_keywords }}">
                <span>{{ category.1 }}</span>
            </a>
        </div>
        {% endfor %}
    </div>
    <div style="justify-content: center; text-align: center;">
        <a class="btn-default" href="{{ url_for('main.index') }}">Reset selection</a>
    </div>
    
    <!-- Events Section -->
    <div class="container mt-5">
        <h2 class="text-left">Top Trending Food Events</h2>
        <div class="trending-events" id="eventContainer">
            <!-- Display events -->
             {% for event in events %}

                {% include "./partials/event_card.html" %}

             {% endfor %}
        </div>
    </div>

    

    <!-- JavaScript to Show More Events -->
    <script>
        function search(){
            search_keywords = document.getElementById("searchInput").value;
            
            window.location.replace("{{ url_for('main.index') }}?category={{ category }}&search_keywords=" + search_keywords);
        }

    </script>

{% endblock %}

website/templates/order.html
{% extends 'base.html' %}

{% block content %}

<div class="login-page">
    <div class="login-container">
        <h2 class="login-title">Order Placed</h2>
        <div>
            <h4><strong>Order number: </strong>{{ order.id }}</h4>
            <p><strong>You're going to: </strong>{{ event.Title }}</p>
            <p><strong>Date & Time: </strong>{{ event.Start_date }}: {{ event.Start_time }}</p>
            <p><strong>Location: </strong>{{ event.Venue }}</p>
            <p><strong>Tickets: </strong>{{ order.tickets }}</p>
        </div>
        <div class="register-link">
            <a href="{{ url_for('main.index') }}">Return home</a>
        </div>
    </div>
</div>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <!-- Profile Container -->
    <div class="container profile-container">
        <div class="profile-header">
            <h2>{{ user.name }}</h2>
            <p>Email: {{ user.emailid }}</p> 
        </div>

        <!-- Profile Options -->
        <a href="{{ url_for('main.history') }}" class="btn-profile">Booking History</a>
        <a href="{{ url_for('main.history2') }}" class="btn-profile">Event creation History</a>
        <a href="{{ url_for('auth.logout') }}" class="btn-logout">Logout</a>
    </div>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="login-page" >

    <!-- Register Form -->
    <div class="register-container">
        <h2 class="register-title">Register</h2>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-danger">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
        <form method="POST">
            {{ form.csrf_token }}
    
            {% if form.username %}
                <div class="mb-3">
                    <label for="username" class="form-label">{{ form.username.label }}</label>
                    {{ form.username(class="form-control", id="username", placeholder="Choose a username") }}
                </div>
            {% endif %}
    
            {% if form.email %}
                <div class="mb-3">
                    <label for="email" class="form-label">{{ form.email.label }}</label>
                    {{ form.email(class="form-control", id="email", placeholder="Enter your email") }}
                </div>
            {% endif %}
    
            {% if form.password %}
                <div class="mb-3">
                    <label for="password" class="form-label">{{ form.password.label }}</label>
                    {{ form.password(class="form-control", id="password", placeholder="Create a password") }}
                </div>
            {% endif %}
    
            {% if form.confirm_password %}
                <div class="mb-3">
                    <label for="confirm_password" class="form-label">{{ form.confirm_password.label }}</label>
                    {{ form.confirm_password(class="form-control", id="confirm-password", placeholder="Confirm your password") }}
                </div>
            {% endif %}
    
            <button type="submit" class="btn btn-default">Register</button>
            
            <div class="login-link">
                <p>Already have an account? <a href="login">Login here</a></p>
            </div>
        </form>
    </div>

</div>
{% endblock %}

website/templates/user.html

{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="login-page">
    <div class="login-container">
        <h2 class="login-title">Login</h2>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-danger">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="col-md-6 form-group">
            {{wtf.quick_form(form)}}
        </div>
        <div class="register-link">
            <p>New user? <a href="{{ url_for('auth.register') }}">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}